#! bin/zsh

# Aliases
# Navigation
alias windows="cd /mnt/c/Users/huacc/Downloads"

# Updates
alias update="brew update && brew doctor && brew upgrade && brew upgrade --cask && brew cleanup -s && brew doctor"
alias update-tools="curl -fsSL https://ollama.com/install.sh | sh && curl -sSL https://install.python-poetry.org | python3 -"

# Commands
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -iv'
alias mkdir='mkdir -p'
alias ps='ps auxf'
alias ping='ping -c 10'
alias less='less -R'
alias grep="grep --color=auto"
alias vi="nvim"
alias vim="nvim"
alias editor="nvim"
alias cat="bat --color=always --theme=Dracula --style=full --paging=always"

# Search command line history
alias h="history | grep "

# Search running processes
alias p="ps aux | grep "
alias topcpu="/bin/ps -eo pcpu,pid,user,args | sort -k 1 -r | head -10"

# Search files in the current folder
alias f="find . | grep "
alias tree="tree -AC --filesfirst"
alias atree="tree -AC --filesfirst -a"

# Tmux
alias tmux="tmux -f ~/.config/tmux.conf"
alias tmuxk="tmux kill-session -t"
alias tmuxs="tmux switch -t"
alias tmuxsu='tmux split-window -v -c "#{pane_current_path}"; tmux select-pane -U'
alias tmuxsd='tmux split-window -v -c "#{pane_current_path}"; tmux select-pane -D'
alias tmuxsl='tmux split-window -h -c "#{pane_current_path}"; tmux select-pane -L'
alias tmuxsr='tmux split-window -h -c "#{pane_current_path}"; tmux select-pane -R'
